""" ConfirmaPercurso_ui.py --

 UI generated by GUI Builder Build 146 on 2009-04-28 23:04:58 from:
    ConfirmaPercurso.ui
THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
The associated callback file should be modified instead.
"""

import Tkinter
import os # needed for relative image paths

# Using new-style classes: create empty base class object
# for compatibility with older python interps
#if sys.version_info < (2, 2):
#    class object:
#        pass

class ConfirmaPercurso(object):
    _images = [] # Holds image refs to prevent GC
    def __init__(self, root):


        # Widget Initialization
        self._button_1 = Tkinter.Button(root,
            default = "active",
            text = "Ok",
        )
        self._button_2 = Tkinter.Button(root,
            text = "Cancela",
        )
        self._label_1 = Tkinter.Label(root,
            text = "Confirma percurso ?",
        )

        # widget commands

        self._button_1.configure(
            command = self._button_1_command
        )
        self._button_2.configure(
            command = self._button_2_command
        )


        # Geometry Management
        self._button_1.grid(
            in_    = root,
            column = 1,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_2.grid(
            in_    = root,
            column = 2,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._label_1.grid(
            in_    = root,
            column = 1,
            row    = 1,
            columnspan = 2,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )


        # Resize Behavior
        root.grid_rowconfigure(1, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(2, weight = 0, minsize = 40, pad = 0)
        root.grid_columnconfigure(1, weight = 0, minsize = 63, pad = 0)
        root.grid_columnconfigure(2, weight = 0, minsize = 40, pad = 0)


