""" selectCab_ui.py --

 UI generated by GUI Builder Build 146 on 2009-04-29 22:03:08 from:
    selectCab.ui
THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
The associated callback file should be modified instead.
"""

import Tkinter
import os # needed for relative image paths

# Using new-style classes: create empty base class object
# for compatibility with older python interps
#if sys.version_info < (2, 2):
#    class object:
#        pass

class SelectCab(object):
    _images = [] # Holds image refs to prevent GC
    def __init__(self, root):


        # Widget Initialization
        self._frame_2 = Tkinter.Frame(root,
        )
        self._label_1 = Tkinter.Label(self._frame_2,
            text = "Selecione a cabeceira de pouso:",
        )
        self._button_2 = Tkinter.Button(root,
            text = "Ok",
        )
        self._button_3 = Tkinter.Button(root,
            text = "Cancela",
        )
        self._radiobutton_1 = Tkinter.Radiobutton(root,
            text = "Cab 1",
            textvariable = self.self.szTxt1,
        )
        self._radiobutton_2 = Tkinter.Radiobutton(root,
            text = "Cab 2",
            textvariable = self.self._szTxt2,
        )

        # widget commands

        self._button_2.configure(
            command = self._button_2_command
        )
        self._button_3.configure(
            command = self._button_3_command
        )
        self._radiobutton_1.configure(
            command = self._radiobutton_1_command
        )
        self._radiobutton_2.configure(
            command = self._radiobutton_2_command
        )


        # Geometry Management
        self._frame_2.grid(
            in_    = root,
            column = 1,
            row    = 1,
            columnspan = 2,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._label_1.grid(
            in_    = self._frame_2,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_2.grid(
            in_    = root,
            column = 1,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_3.grid(
            in_    = root,
            column = 2,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._radiobutton_1.grid(
            in_    = root,
            column = 1,
            row    = 2,
            columnspan = 2,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._radiobutton_2.grid(
            in_    = root,
            column = 1,
            row    = 3,
            columnspan = 2,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )


        # Resize Behavior
        root.grid_rowconfigure(1, weight = 0, minsize = 36, pad = 0)
        root.grid_rowconfigure(2, weight = 0, minsize = 20, pad = 0)
        root.grid_rowconfigure(3, weight = 0, minsize = 33, pad = 0)
        root.grid_rowconfigure(4, weight = 0, minsize = 32, pad = 0)
        root.grid_columnconfigure(1, weight = 0, minsize = 149, pad = 0)
        root.grid_columnconfigure(2, weight = 0, minsize = 2, pad = 0)
        self._frame_2.grid_rowconfigure(1, weight = 0, minsize = 28, pad = 0)
        self._frame_2.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)


