#!/usr/bin/env python
""" selectCab.py --

 UI generated by GUI Builder Build 146 on 2009-04-29 22:03:08 from:
    selectCab.ui
 This file is auto-generated.  Only the code within
    '# BEGIN USER CODE (global|class)'
    '# END USER CODE (global|class)'
 and code inside the callback subroutines will be round-tripped.
 The 'main' function is reserved.
"""

from Tkinter import *
from selectCab_ui import SelectCab

# BEGIN USER CODE global

# END USER CODE global

class CustomSelectCab(SelectCab):
    pass

    # BEGIN CALLBACK CODE
    # ONLY EDIT CODE INSIDE THE def FUNCTIONS.

    # _button_2_command --
    #
    # Callback to handle _button_2 widget option -command
    def _button_2_command(self, *args):
        pass

    # _button_3_command --
    #
    # Callback to handle _button_3 widget option -command
    def _button_3_command(self, *args):
        pass

    # _radiobutton_1_command --
    #
    # Callback to handle _radiobutton_1 widget option -command
    def _radiobutton_1_command(self, *args):
        pass

    # _radiobutton_2_command --
    #
    # Callback to handle _radiobutton_2 widget option -command
    def _radiobutton_2_command(self, *args):
        pass

    # END CALLBACK CODE

    # BEGIN USER CODE class

    # END USER CODE class

def main():
    # Standalone Code Initialization
    # DO NOT EDIT
    try: userinit()
    except NameError: pass
    root = Tk()
    demo = CustomSelectCab(root)
    root.title('selectCab')
    try: run()
    except NameError: pass
    root.protocol('WM_DELETE_WINDOW', root.quit)
    root.mainloop()

if __name__ == '__main__': main()
